### ISSUE TITLE
Payment expired early [server time issues]

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/woocommerce-plugin#191]
*get_order* will return existing elapsed time from server in seconds. Client will then count forward from that

Time used in [websocket call](https://github.com/blockonomics/woocommerce-plugin/blob/396812db4650c3c71ce040ecba9213e373f2cad4/js/app.js#L238) is unnecessary and can be removed

Check any further places of timestamp use that maybe causing problems

**Comment by DarrenWestwood** [comment]
### New Design


- The call to `get_order` should calculate the remaining time for the order and return the _remaining_time_ along with the order info instead of the _timestamp_.
- The client side should count/tick down from the _remaining_time_ to 0.
- Remove unnecessary passing of _blockonomics_time_period_ from the template and js: https://github.com/blockonomics/woocommerce-plugin/blob/191f029561be6d118ae9ef4286ca9bbf2c6175a7/templates/blockonomics_checkout.php#L122
- Remove the timestamp from the websocket. Verify all places the timestamp is used and check no problems are caused

**Comment by shivaenigma** [comment]
Update the *timestamp* param from server shouldn't get removed. It is used to get the correct txid of payment payment (in case customer refersh the page at a very later time). 
We can send a new *remaining_time* parameter
