### ISSUE TITLE
Warning: Payment arrived after

### ISSUE THREAD

**Issue by Undersidedog2** [blockonomics/woocommerce-plugin#33]
Hello, i have this kinda error. For example order is done at 1:08am (i have changed payment countdown to 30 minutes) and customer paid money on 1:29 (I have set status[confirmations] to 0). Sites gives me a warning in notes Warning: Payment arrived after 21.25 minutes. Received BTC may not match current bitcoin price

**Comment by Undersidedog2** [comment]
Why does it makes ?

**Comment by blockonomics** [comment]
This was put in the code so that zero confirmation arrives within 10 minutes. In you case you need to do the following changes:
- Change _600_ to _1800_ on [this line](https://github.com/blockonomics/woocommerce-plugin/blob/master/blockonomics-woocommerce.php#L240)
- Change _elseif_ to _if_ on [this line](https://github.com/blockonomics/woocommerce-plugin/blob/master/blockonomics-woocommerce.php#L244)
